[phases.setup]
nixPkgs = ["php84", "php84Extensions.mysqli", "php84Extensions.pdo", "php84Extensions.pdo_mysql", "php84Extensions.mbstring", "php84Extensions.tokenizer"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t /app"
